name: Jest Testing/Coverage

on:
  push:
    branches: 
      - main
      - develop
  pull_request:
    branches: 
      - main

  workflow_dispatch:

jobs:
  testdevelop:
    name: Run tests in develop branch
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@develop

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test -- --coverage --watchAll=false

  testmain:
    name: Run tests in main branch
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test -- --coverage --watchAll=false
